

//  ---------- INLCUDED BLOCK: mux11_1  ---------- 
module mux11_1 (
  input  wire [3:0]  sel,
  input  wire [31:0] in0, in1, in2, in3, in4,
  input  wire [31:0] in5, in6, in7, in8, in9, in10,
  output reg  [31:0] out
);

    always @(*) begin
        case (sel)
            4'd0  : out = in0;
            4'd1  : out = in1;
            4'd2  : out = in2;
            4'd3  : out = in3;
            4'd4  : out = in4;
            4'd5  : out = in5;
            4'd6  : out = in6;
            4'd7  : out = in7;
            4'd8  : out = in8;
            4'd9  : out = in9;
            4'd10 : out = in10;
          default: out = 32'b0; // ou out = in0; (depende da política)
        endcase
    end

endmodule



//  ---------- INLCUDED BLOCK: adder32  ---------- 
module adder32 (
    input  wire        carry_in,
    input  wire [31:0] a,
    input  wire [31:0] b,   
    output wire [31:0] sum,
    output wire        carry_out
);
    assign {carry_out, sum} = a + b + carry_in;
endmodule



//  ---------- INLCUDED BLOCK: sub32  ---------- 
module sub32 (
    input  wire [31:0] a,
    input  wire [31:0] b,
    output wire [31:0] diff,
    output wire        borrow   // indica se houve "empréstimo" (underflow em unsigned)
);
    wire [31:0] b_inverted;
    wire        carry_out;

    // Complemento de dois: ~b + 1 é feito pelo somador com carry_in=1
    assign b_inverted = ~b;

    adder32 u_adder (
        .a         (a),
        .b         (b_inverted),
        .carry_in  (1'b1),     // soma +1
        .sum       (diff),
        .carry_out (carry_out)
    );

    // Em subtração, o "borrow" é o inverso do carry_out (para unsigned)
    assign borrow = ~carry_out;
endmodule



//  ---------- INLCUDED BLOCK: and32  ---------- 
module and32 (
  input  wire [31:0] a,
  input  wire [31:0] b,
  output wire [31:0] y
);
    assign y = a & b;
endmodule



//  ---------- INLCUDED BLOCK: or32  ---------- 
module or32 (
  input  wire [31:0] a,
  input  wire [31:0] b,
  output wire [31:0] y
);
    assign y = a | b;
endmodule



//  ---------- INLCUDED BLOCK: xor32  ---------- 
module xor32 (
  input  wire [31:0] a,
  input  wire [31:0] b,
  output wire [31:0] y
);
    assign y = a ^ b;
endmodule



//  ---------- INLCUDED BLOCK: sll32  ---------- 
module sll32 (
    input  wire [31:0] a,
    input  wire [4:0]  desloc,
    output wire [31:0] y
);
    assign y = a << desloc;
endmodule



//  ---------- INLCUDED BLOCK: srl32  ---------- 
module srl32 (
    input  wire [31:0] a,
    input  wire [4:0]  desloc,
    output wire [31:0] y
);
    assign y = a >> desloc;
endmodule



//  ---------- INLCUDED BLOCK: sra32  ---------- 
module sra32 (
    input  wire signed [31:0] a,
    input  wire [4:0]        desloc,
    output wire signed [31:0] y
);
    assign y = a >>> desloc;
endmodule



//  ---------- INLCUDED BLOCK: slt32  ---------- 
module slt32 (
    input  wire signed [31:0] a,
    input  wire signed [31:0] b,
    output wire [31:0] y
);
    assign y = (a < b) ? 32'd1 : 32'd0;
endmodule



//  ---------- INLCUDED BLOCK: sltu32  ---------- 
module sltu32 (
    input  wire [31:0] a,
    input  wire [31:0] b,
    output wire [31:0] y
);
    assign y = (a < b) ? 32'd1 : 32'd0;
endmodule



//  ---------- INLCUDED BLOCK: passb32  ---------- 
module passb32 (
    input  wire [31:0] b,
    output wire [31:0] y
);
    assign y = b;
endmodule


// Automatically generated by ChipInventor Cloud EDA Tool - 3.15
// Careful: this file (hdl.v) will be automatically replaced
// when you ask tool to generate top Verilog code by clicking
// at BLOCKS button.

module top (

  input wire [31:0] A,
  input wire [31:0] B,
  output wire carry,
  input wire [3:0] sel,
  output wire borrow,
  output wire [31:0] mux_out,
  input wire [4:0] desloc

);

//Internal Wires
 wire [31:0] w_1;
 wire [31:0] w_2;
 wire [31:0] w_3;
 wire [31:0] w_4;
 wire [31:0] w_5;
 wire [31:0] w_6;
 wire [31:0] w_7;
 wire [31:0] w_8;
 wire [31:0] w_9;
 wire [31:0] w_10;
 wire [31:0] w_11;

//Instances of Modules
and32 blk4158_51 (
         .a (A[31:0]),
         .b (B[31:0]),
         .y (w_1)
     );

or32 blk4159_52 (
         .a (A[31:0]),
         .b (B[31:0]),
         .y (w_2)
     );

xor32 blk4161_53 (
         .a (A[31:0]),
         .b (B[31:0]),
         .y (w_3)
     );

slt32 blk4165_57 (
         .a (A[31:0]),
         .b (B[31:0]),
         .y (w_4)
     );

sltu32 blk4166_58 (
         .a (A[31:0]),
         .b (B[31:0]),
         .y (w_5)
     );

passb32 blk4167_59 (
         .b (B[31:0]),
         .y (w_6)
     );

adder32 blk4014_62 (
         .a (A[31:0]),
         .b (B[31:0]),
         .carry_out (carry),
         .carry_in (1'b0),
         .sum (w_7)
     );

srl32 blk4163_63 (
         .a (A[31:0]),
         .desloc (desloc[4:0]),
         .y (w_8)
     );

sll32 blk4162_64 (
         .a (A[31:0]),
         .desloc (desloc[4:0]),
         .y (w_9)
     );

sra32 blk4164_65 (
         .a (A[31:0]),
         .desloc (desloc[4:0]),
         .y (w_10)
     );

mux11_1 blk4013_68 (
         .sel (sel[3:0]),
         .out (mux_out[31:0]),
         .in2 (w_1),
         .in3 (w_2),
         .in4 (w_3),
         .in8 (w_4),
         .in9 (w_5),
         .in10 (w_6),
         .in0 (w_7),
         .in6 (w_8),
         .in5 (w_9),
         .in7 (w_10),
         .in1 (w_11)
     );

sub32 blk4021_69 (
         .a (A[31:0]),
         .b (B[31:0]),
         .borrow (borrow),
         .diff (w_11)
     );


endmodule
